kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "motioneye.fullname" . }}-config

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
